from django.urls import path
from . import views

urlpatterns = [
    path('', views.novel_list_view, name='novel_list'),
    path('archived/', views.archived_novel_list_view, name='archived_novel_list'),
    path('create/', views.novel_create_view, name='novel_create'),
    path('<int:pk>/', views.novel_detail_view, name='novel_detail'),
    path('<int:pk>/edit/', views.novel_update_view, name='novel_edit'),
    path('<int:pk>/delete/', views.novel_delete_view, name='novel_delete'),
    path('<int:pk>/archive/', views.novel_archive_view, name='novel_archive'),
    path('<int:pk>/unarchive/', views.novel_unarchive_view, name='novel_unarchive'),
    path('<int:novel_pk>/part/create/', views.part_create_view, name='part_create'),
    path('<int:novel_pk>/part/<int:part_pk>/', views.part_detail_view, name='part_detail'),
    path('<int:novel_pk>/part/<int:part_pk>/edit/', views.part_edit_view, name='part_edit'),
    path('<int:novel_pk>/chapter/create/', views.chapter_create_view, name='chapter_create'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/', views.chapter_detail_view, name='chapter_detail'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/edit/', views.chapter_edit_view, name='chapter_edit'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/archive/', views.chapter_archive_view, name='chapter_archive'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/restore/', views.chapter_restore_view, name='chapter_restore'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/delete/', views.chapter_delete_view, name='chapter_delete'),
    path('<int:novel_pk>/chapters/archived/', views.archived_chapter_list_view, name='archived_chapter_list'),
    path('<int:novel_pk>/chapters/reorder/', views.chapter_reorder_view, name='chapter_reorder'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scene/create/', views.scene_create_view, name='scene_create'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scene/<int:scene_pk>/editor/', views.scene_editor_view, name='scene_editor'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scene/<int:scene_pk>/edit/', views.scene_edit_view, name='scene_edit'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scene/<int:scene_pk>/archive/', views.scene_archive_view, name='scene_archive'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scene/<int:scene_pk>/restore/', views.scene_restore_view, name='scene_restore'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scene/<int:scene_pk>/delete/', views.scene_delete_view, name='scene_delete'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scenes/archived/', views.archived_scene_list_view, name='archived_scene_list'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scenes/reorder/', views.scene_reorder_view, name='scene_reorder'),
    path('<int:novel_pk>/chapter/<int:chapter_pk>/scene/<int:scene_pk>/save/', views.scene_save_view, name='scene_save'),
    path('<int:novel_pk>/scene/<int:scene_pk>/move/', views.scene_move_view, name='scene_move'),
]
