# Generated by Django 5.2.10 on 2026-01-29 20:48

import django.db.models.deletion
import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_roles', to='novels.novel')),
            ],
            options={
                'verbose_name': 'Character Role',
                'verbose_name_plural': 'Character Roles',
                'ordering': ['order', 'name'],
                'unique_together': {('novel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Physical description, personality, background (markdown supported)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the character (markdown supported)')),
                ('interview', models.TextField(blank=True, help_text='Interview with the character (markdown supported)')),
                ('personality', models.TextField(blank=True, help_text='Personality traits (markdown supported)')),
                ('relationships', models.TextField(blank=True, help_text='Relationships with other characters (markdown supported)')),
                ('image', models.ImageField(blank=True, help_text='Character portrait or reference image', null=True, upload_to=planning.models.character_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.novel')),
                ('role', models.ForeignKey(blank=True, help_text="Character's role in the story", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='planning.characterrole')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='novels.novel')),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'ordering': ['order', 'name'],
                'unique_together': {('novel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the item (markdown supported)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the item (markdown supported)')),
                ('image', models.ImageField(blank=True, help_text='Item image or reference', null=True, upload_to=planning.models.item_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='novels.novel')),
                ('type', models.ForeignKey(blank=True, help_text='Type of item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='planning.itemtype')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_types', to='novels.novel')),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'ordering': ['order', 'name'],
                'unique_together': {('novel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the location (markdown supported)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the location (markdown supported)')),
                ('image', models.ImageField(blank=True, help_text='Location image or map', null=True, upload_to=planning.models.location_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='novels.novel')),
                ('type', models.ForeignKey(blank=True, help_text='Type of location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='planning.locationtype')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
    ]
