# Generated by Django 6.0 on 2026-03-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('novels', '0002_add_scene_status'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_object_id', models.PositiveIntegerField()),
                ('to_object_id', models.PositiveIntegerField()),
                ('label', models.CharField(help_text="Forward label e.g. 'owns'", max_length=100)),
                ('reverse_label', models.CharField(help_text="Reverse label e.g. 'owned by'", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='contenttypes.contenttype')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='novels.novel')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_label', models.CharField(help_text="e.g. 'owns', 'lives in', 'enemy of'", max_length=100)),
                ('reverse_label', models.CharField(help_text="e.g. 'owned by', 'home of', 'enemy of'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_types', to='novels.novel')),
            ],
            options={
                'ordering': ['order', 'forward_label'],
                'unique_together': {('novel', 'forward_label')},
            },
        ),
    ]
