# Generated by Django 6.0 on 2026-03-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('novels', '0002_add_scene_status'),
        ('planning', '0002_relationship_relationshiptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('mention_count', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_occurrences', to='contenttypes.contenttype')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_entities', to='novels.scene')),
            ],
            options={
                'ordering': ['content_type', 'object_id'],
                'unique_together': {('scene', 'content_type', 'object_id')},
            },
        ),
    ]
