# Generated by Django 6.0.3 on 2026-05-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_add_order_to_planning_entities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['order', 'last_name', 'first_name'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
