# Generated by Django 6.0.3 on 2026-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_character_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='arc_in_story',
            field=models.TextField(blank=True, help_text="The character's arc in the story (markdown supported)"),
        ),
        migrations.AddField(
            model_name='character',
            name='fears_and_weaknesses',
            field=models.TextField(blank=True, help_text='Fears and weaknesses of the character (markdown supported)'),
        ),
        migrations.AddField(
            model_name='character',
            name='goals_and_motivations',
            field=models.TextField(blank=True, help_text='Goals and motivations of the character (markdown supported)'),
        ),
        migrations.AddField(
            model_name='character',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='physical_description',
            field=models.TextField(blank=True, help_text='Physical description of the character (markdown supported)'),
        ),
        migrations.AddField(
            model_name='character',
            name='the_lie_they_believe',
            field=models.TextField(blank=True, help_text='The lie the character believes about themselves or the world (markdown supported)'),
        ),
        migrations.AddField(
            model_name='item',
            name='history',
            field=models.TextField(blank=True, help_text='History of the item (markdown supported)'),
        ),
        migrations.AddField(
            model_name='item',
            name='properties_and_abilities',
            field=models.TextField(blank=True, help_text='Properties and abilities of the item (markdown supported)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, help_text='General description of the character (markdown supported)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True, help_text='[No longer in use] Personality traits'),
        ),
        migrations.AlterField(
            model_name='character',
            name='relationships',
            field=models.TextField(blank=True, help_text='[No longer in use] Free-text relationships field, superseded by the Relationship model'),
        ),
    ]
