# Generated by Django 6.0.5 on 2026-06-02 07:17

import django.db.models.deletion
import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_rename_summary_part_description_and_more'),
        ('planning', '0006_character_arc_in_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_building_types', to='novels.novel')),
            ],
            options={
                'verbose_name': 'World Building Type',
                'verbose_name_plural': 'World Building Types',
                'ordering': ['order', 'name'],
                'unique_together': {('novel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorldBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the world building item (markdown supported)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the world building item (markdown supported)')),
                ('image', models.ImageField(blank=True, help_text='Image for the world building item', null=True, upload_to=planning.models.world_building_image_path)),
                ('order', models.IntegerField(default=0, help_text='Display order within the novel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_building_items', to='novels.novel')),
                ('type', models.ForeignKey(blank=True, help_text='Type of world building item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_building_items', to='planning.worldbuildingtype')),
            ],
            options={
                'verbose_name': 'World Building Item',
                'verbose_name_plural': 'World Building Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
