services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PROJECTDIR}:/code
      - ${PROJECTDIR}/media:/code/media
    ports:
      - "6080:8000"
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=True
