services:
  web:
    image: novelapp:latest
    command: gunicorn novelapp.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - /home/dhollingworth/django-projects/novel-it/novelapp:/code
      - /home/dhollingworth/django-projects/novel-it/novelapp/media:/code/media
    ports:
      - "6080:8000"
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=True
