# Generated by Django 5.2.10 on 2026-01-29 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Synopsis or description of the novel')),
                ('premise', models.TextField(blank=True, help_text='Premise or theme of the novel')),
                ('genre', models.CharField(blank=True, help_text='Genre of the novel', max_length=100)),
                ('word_count', models.IntegerField(default=0, help_text='Total word count (calculated from scenes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novel',
                'verbose_name_plural': 'Novels',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order within the novel')),
                ('summary', models.TextField(blank=True, help_text='Chapter summary or notes')),
                ('word_count', models.IntegerField(default=0, help_text='Total word count (calculated from scenes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['order'],
                'unique_together': {('novel', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order within the chapter')),
                ('content', models.TextField(blank=True, help_text='Markdown content of the scene')),
                ('notes', models.TextField(blank=True, help_text='Scene notes or summary')),
                ('word_count', models.IntegerField(default=0, help_text='Word count of content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='novels.chapter')),
            ],
            options={
                'verbose_name': 'Scene',
                'verbose_name_plural': 'Scenes',
                'ordering': ['order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
    ]
