# Generated by Django 6.0 on 2026-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('first_draft', 'First Draft'), ('needs_review', 'Needs Review'), ('final_draft', 'Final Draft'), ('complete', 'Complete')], default='not_started', max_length=20),
        ),
    ]
