# Generated by Django 6.0.3 on 2026-04-03 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_add_scene_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('plotting', 'Plotting'), ('first_draft', 'First Draft'), ('first_review', 'First Review'), ('second_draft', 'Second Draft'), ('second_review', 'Second Review'), ('structural_edit', 'Structural Edit'), ('final_edit', 'Final Edit'), ('beta_reading', 'Beta Reading'), ('publishing', 'Publishing'), ('published', 'Published')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='novel',
            name='parts_enabled',
            field=models.BooleanField(default=False, help_text='Whether parts are enabled for this novel'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within the part'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True, help_text='Chapter summary'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('plotting', 'Plotting'), ('first_draft', 'First Draft'), ('first_review', 'First Review'), ('second_draft', 'Second Draft'), ('second_review', 'Second Review'), ('structural_edit', 'Structural Edit'), ('final_edit', 'Final Edit'), ('beta_reading', 'Beta Reading'), ('publishing', 'Publishing'), ('published', 'Published')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('plotting', 'Plotting'), ('first_draft', 'First Draft'), ('first_review', 'First Review'), ('second_draft', 'Second Draft'), ('second_review', 'Second Review'), ('structural_edit', 'Structural Edit'), ('final_edit', 'Final Edit'), ('beta_reading', 'Beta Reading'), ('publishing', 'Publishing'), ('published', 'Published')], default='not_started', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='novels.novel')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['order'],
                'unique_together': {('novel', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chapter',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.part'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('part', 'order')},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='novel',
        ),
    ]
