# Generated by Django 6.0.3 on 2026-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_novel_missing_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='summary',
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, help_text='Chapter description'),
        ),
        migrations.AddField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, help_text='Scene description'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.TextField(blank=True, help_text='Synopsis of the novel'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='notes',
            field=models.TextField(blank=True, help_text='Scene notes'),
        ),
    ]
